version: "3"

services:
  user-frontend:
    build:
      context: .
      dockerfile: ./packages/user/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:3002/
    command: npm run dev
    volumes:
      - ./packages/user:/app/packages/user


  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/backend:/app/packages/backend
